PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cpo: <http://purl.obolibrary.org/obo/cpo#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT (?type as ?ids)
WHERE {
  ?type a ?Class
  FILTER (regex (str(?type), "cpo") && regex (str(?type), "[0-9]"))
}
ORDER BY DESC(?type)
LIMIT 10
